#!/usr/bin/bash

# For Arch:

### https://aur.archlinux.org/packages/rtl88x2bu-dkms-git/ ###

# For deb:

mkdir -p ~/git
cd ~/git
git clone https://github.com/RinCat/RTL88x2BU-Linux-Driver
cd RTL88x2BU-Linux-Driver
make clean
make -j8

sudo make install

#You can try use modprobe 88x2bu rtw_switch_usb_mode=1 to force the adapter run under USB 3.0. But if your adapter/port/motherboard not support it, the driver will be in restart loop. Remove the parameter and reload the driver to restore. Alternatively, modprobe 88x2bu rtw_switch_usb_mode=2 let's it run as USB 2 device.

#If you want to force a given mode permanently (even when switching the adapter across devices), create the file /etc/modprobe.d/99-RTL88x2BU.conf with the following content: options 88x2bu rtw_switch_usb_mode=1